language: ruby
services: mysql
before_script:
  - mysql -u root -e "CREATE DATABASE rdo;"
  - mysql -u root -e "GRANT ALL ON rdo.* TO rdo@localhost IDENTIFIED BY 'rdo';"
script: "bundle exec rake spec"
rvm:
  - 1.9.2
  - 1.9.3
notifications:
  email: chris@w3style.co.uk
